/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'
import { Route as AuthenticatedStoreMembershipRouteImport } from './routes/_authenticated/store/membership/route'
import { Route as AuthenticatedStoreEditorRouteImport } from './routes/_authenticated/store/editor/route'
import { Route as AuthenticatedStoreCollectionsRouteImport } from './routes/_authenticated/store/collections/route'
import { Route as AuthenticatedStoreBillingHistoryIndexImport } from './routes/_authenticated/store/billing-history/index'

// Create Virtual Routes

const AuthCallbackIndexLazyImport = createFileRoute('/auth-callback/')()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authResetPasswordLazyImport = createFileRoute('/(auth)/reset-password')()
const authProfileLazyImport = createFileRoute('/(auth)/profile')()
const authOnboardingLazyImport = createFileRoute('/(auth)/onboarding')()
const authHomepageLazyImport = createFileRoute('/(auth)/homepage')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const PagesPrivacyIndexLazyImport = createFileRoute('/pages/privacy/')()
const PagesMakeyourbrandIndexLazyImport = createFileRoute(
  '/pages/make_your_brand/',
)()
const PagesGettingStartedIndexLazyImport = createFileRoute(
  '/pages/getting-started/',
)()
const PagesFulfillmentPageIndexLazyImport = createFileRoute(
  '/pages/fulfillment-page/',
)()
const PagesForCreatorsIndexLazyImport = createFileRoute(
  '/pages/for-creators/',
)()
const PagesCreatorStoreIndexLazyImport = createFileRoute(
  '/pages/creator-store/',
)()
const PagesCreatingProductsIndexLazyImport = createFileRoute(
  '/pages/creating-products/',
)()
const PagesCareersIndexLazyImport = createFileRoute('/pages/careers/')()
const PagesAboutUsIndexLazyImport = createFileRoute('/pages/about-us/')()
const AuthenticatedStoreIndexLazyImport = createFileRoute(
  '/_authenticated/store/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedProductsIndexLazyImport = createFileRoute(
  '/_authenticated/products/',
)()
const AuthenticatedProductCatalogIndexLazyImport = createFileRoute(
  '/_authenticated/productCatalog/',
)()
const AuthenticatedPayoutsIndexLazyImport = createFileRoute(
  '/_authenticated/payouts/',
)()
const AuthenticatedOrdersIndexLazyImport = createFileRoute(
  '/_authenticated/orders/',
)()
const AuthenticatedHelpCenterIndexLazyImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedDashboardIndexLazyImport = createFileRoute(
  '/_authenticated/dashboard/',
)()
const AuthenticatedCustomersIndexLazyImport = createFileRoute(
  '/_authenticated/customers/',
)()
const AuthenticatedChatsIndexLazyImport = createFileRoute(
  '/_authenticated/chats/',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedProductsCreateproductLazyImport = createFileRoute(
  '/_authenticated/products/createproduct',
)()
const AuthenticatedProductsIdLazyImport = createFileRoute(
  '/_authenticated/products/$id',
)()
const AuthenticatedProductCatalogIdLazyImport = createFileRoute(
  '/_authenticated/productCatalog/$id',
)()
const AuthenticatedOrdersIdLazyImport = createFileRoute(
  '/_authenticated/orders/$id',
)()
const AuthenticatedDesignerCreateLazyImport = createFileRoute(
  '/_authenticated/designer/create',
)()
const AuthenticatedDesignerIdLazyImport = createFileRoute(
  '/_authenticated/designer/$id',
)()
const AuthenticatedStoreMembershipIndexLazyImport = createFileRoute(
  '/_authenticated/store/membership/',
)()
const AuthenticatedStoreEditorIndexLazyImport = createFileRoute(
  '/_authenticated/store/editor/',
)()
const AuthenticatedStoreCollectionsIndexLazyImport = createFileRoute(
  '/_authenticated/store/collections/',
)()
const AuthenticatedProductCatalogProductsIndexLazyImport = createFileRoute(
  '/_authenticated/productCatalog/products/',
)()
const AuthenticatedProductCatalogProductsIdLazyImport = createFileRoute(
  '/_authenticated/productCatalog/products/$id',
)()
const AuthenticatedProductCatalogCategorySlugIndexLazyImport = createFileRoute(
  '/_authenticated/productCatalog/category/$slug/',
)()
const AuthenticatedProductCatalogCategorySlugIdLazyImport = createFileRoute(
  '/_authenticated/productCatalog/category/$slug/$id',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackIndexLazyRoute = AuthCallbackIndexLazyImport.update({
  id: '/auth-callback/',
  path: '/auth-callback/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth-callback/index.lazy').then((d) => d.Route),
)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authResetPasswordLazyRoute = authResetPasswordLazyImport
  .update({
    id: '/(auth)/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/reset-password.lazy').then((d) => d.Route),
  )

const authProfileLazyRoute = authProfileLazyImport
  .update({
    id: '/(auth)/profile',
    path: '/profile',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/profile.lazy').then((d) => d.Route))

const authOnboardingLazyRoute = authOnboardingLazyImport
  .update({
    id: '/(auth)/onboarding',
    path: '/onboarding',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/onboarding.lazy').then((d) => d.Route))

const authHomepageLazyRoute = authHomepageLazyImport
  .update({
    id: '/(auth)/homepage',
    path: '/homepage',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/homepage.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const PagesPrivacyIndexLazyRoute = PagesPrivacyIndexLazyImport.update({
  id: '/pages/privacy/',
  path: '/pages/privacy/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pages/privacy/index.lazy').then((d) => d.Route),
)

const PagesMakeyourbrandIndexLazyRoute =
  PagesMakeyourbrandIndexLazyImport.update({
    id: '/pages/make_your_brand/',
    path: '/pages/make_your_brand/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/pages/make_your_brand/index.lazy').then((d) => d.Route),
  )

const PagesGettingStartedIndexLazyRoute =
  PagesGettingStartedIndexLazyImport.update({
    id: '/pages/getting-started/',
    path: '/pages/getting-started/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/pages/getting-started/index.lazy').then((d) => d.Route),
  )

const PagesFulfillmentPageIndexLazyRoute =
  PagesFulfillmentPageIndexLazyImport.update({
    id: '/pages/fulfillment-page/',
    path: '/pages/fulfillment-page/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/pages/fulfillment-page/index.lazy').then((d) => d.Route),
  )

const PagesForCreatorsIndexLazyRoute = PagesForCreatorsIndexLazyImport.update({
  id: '/pages/for-creators/',
  path: '/pages/for-creators/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pages/for-creators/index.lazy').then((d) => d.Route),
)

const PagesCreatorStoreIndexLazyRoute = PagesCreatorStoreIndexLazyImport.update(
  {
    id: '/pages/creator-store/',
    path: '/pages/creator-store/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/pages/creator-store/index.lazy').then((d) => d.Route),
)

const PagesCreatingProductsIndexLazyRoute =
  PagesCreatingProductsIndexLazyImport.update({
    id: '/pages/creating-products/',
    path: '/pages/creating-products/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/pages/creating-products/index.lazy').then((d) => d.Route),
  )

const PagesCareersIndexLazyRoute = PagesCareersIndexLazyImport.update({
  id: '/pages/careers/',
  path: '/pages/careers/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pages/careers/index.lazy').then((d) => d.Route),
)

const PagesAboutUsIndexLazyRoute = PagesAboutUsIndexLazyImport.update({
  id: '/pages/about-us/',
  path: '/pages/about-us/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pages/about-us/index.lazy').then((d) => d.Route),
)

const AuthenticatedStoreIndexLazyRoute =
  AuthenticatedStoreIndexLazyImport.update({
    id: '/store/',
    path: '/store/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/store/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedProductsIndexLazyRoute =
  AuthenticatedProductsIndexLazyImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/products/index.lazy').then((d) => d.Route),
  )

const AuthenticatedProductCatalogIndexLazyRoute =
  AuthenticatedProductCatalogIndexLazyImport.update({
    id: '/productCatalog/',
    path: '/productCatalog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/productCatalog/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedPayoutsIndexLazyRoute =
  AuthenticatedPayoutsIndexLazyImport.update({
    id: '/payouts/',
    path: '/payouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/payouts/index.lazy').then((d) => d.Route),
  )

const AuthenticatedOrdersIndexLazyRoute =
  AuthenticatedOrdersIndexLazyImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/orders/index.lazy').then((d) => d.Route),
  )

const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDashboardIndexLazyRoute =
  AuthenticatedDashboardIndexLazyImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/index.lazy').then((d) => d.Route),
  )

const AuthenticatedCustomersIndexLazyRoute =
  AuthenticatedCustomersIndexLazyImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customers/index.lazy').then((d) => d.Route),
  )

const AuthenticatedChatsIndexLazyRoute =
  AuthenticatedChatsIndexLazyImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chats/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductsCreateproductLazyRoute =
  AuthenticatedProductsCreateproductLazyImport.update({
    id: '/products/createproduct',
    path: '/products/createproduct',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/products/createproduct.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductsIdLazyRoute =
  AuthenticatedProductsIdLazyImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/products/$id.lazy').then((d) => d.Route),
  )

const AuthenticatedProductCatalogIdLazyRoute =
  AuthenticatedProductCatalogIdLazyImport.update({
    id: '/productCatalog/$id',
    path: '/productCatalog/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/productCatalog/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedOrdersIdLazyRoute = AuthenticatedOrdersIdLazyImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/orders/$id.lazy').then((d) => d.Route),
)

const AuthenticatedDesignerCreateLazyRoute =
  AuthenticatedDesignerCreateLazyImport.update({
    id: '/designer/create',
    path: '/designer/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/designer/create.lazy').then((d) => d.Route),
  )

const AuthenticatedDesignerIdLazyRoute =
  AuthenticatedDesignerIdLazyImport.update({
    id: '/designer/$id',
    path: '/designer/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/designer/$id.lazy').then((d) => d.Route),
  )

const AuthenticatedStoreMembershipRouteRoute =
  AuthenticatedStoreMembershipRouteImport.update({
    id: '/store/membership',
    path: '/store/membership',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedStoreEditorRouteRoute =
  AuthenticatedStoreEditorRouteImport.update({
    id: '/store/editor',
    path: '/store/editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedStoreCollectionsRouteRoute =
  AuthenticatedStoreCollectionsRouteImport.update({
    id: '/store/collections',
    path: '/store/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedStoreMembershipIndexLazyRoute =
  AuthenticatedStoreMembershipIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreMembershipRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/store/membership/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedStoreEditorIndexLazyRoute =
  AuthenticatedStoreEditorIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreEditorRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/store/editor/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedStoreCollectionsIndexLazyRoute =
  AuthenticatedStoreCollectionsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreCollectionsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/store/collections/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCatalogProductsIndexLazyRoute =
  AuthenticatedProductCatalogProductsIndexLazyImport.update({
    id: '/productCatalog/products/',
    path: '/productCatalog/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/productCatalog/products/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedStoreBillingHistoryIndexRoute =
  AuthenticatedStoreBillingHistoryIndexImport.update({
    id: '/store/billing-history/',
    path: '/store/billing-history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/store/billing-history/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCatalogProductsIdLazyRoute =
  AuthenticatedProductCatalogProductsIdLazyImport.update({
    id: '/productCatalog/products/$id',
    path: '/productCatalog/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/productCatalog/products/$id.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductCatalogCategorySlugIndexLazyRoute =
  AuthenticatedProductCatalogCategorySlugIndexLazyImport.update({
    id: '/productCatalog/category/$slug/',
    path: '/productCatalog/category/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/productCatalog/category/$slug/index.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedProductCatalogCategorySlugIdLazyRoute =
  AuthenticatedProductCatalogCategorySlugIdLazyImport.update({
    id: '/productCatalog/category/$slug/$id',
    path: '/productCatalog/category/$slug/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/productCatalog/category/$slug/$id.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/homepage': {
      id: '/(auth)/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof authHomepageLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/profile': {
      id: '/(auth)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/auth-callback/': {
      id: '/auth-callback/'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/store/collections': {
      id: '/_authenticated/store/collections'
      path: '/store/collections'
      fullPath: '/store/collections'
      preLoaderRoute: typeof AuthenticatedStoreCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/store/editor': {
      id: '/_authenticated/store/editor'
      path: '/store/editor'
      fullPath: '/store/editor'
      preLoaderRoute: typeof AuthenticatedStoreEditorRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/store/membership': {
      id: '/_authenticated/store/membership'
      path: '/store/membership'
      fullPath: '/store/membership'
      preLoaderRoute: typeof AuthenticatedStoreMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/designer/$id': {
      id: '/_authenticated/designer/$id'
      path: '/designer/$id'
      fullPath: '/designer/$id'
      preLoaderRoute: typeof AuthenticatedDesignerIdLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/designer/create': {
      id: '/_authenticated/designer/create'
      path: '/designer/create'
      fullPath: '/designer/create'
      preLoaderRoute: typeof AuthenticatedDesignerCreateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/productCatalog/$id': {
      id: '/_authenticated/productCatalog/$id'
      path: '/productCatalog/$id'
      fullPath: '/productCatalog/$id'
      preLoaderRoute: typeof AuthenticatedProductCatalogIdLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/products/createproduct': {
      id: '/_authenticated/products/createproduct'
      path: '/products/createproduct'
      fullPath: '/products/createproduct'
      preLoaderRoute: typeof AuthenticatedProductsCreateproductLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/payouts/': {
      id: '/_authenticated/payouts/'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/productCatalog/': {
      id: '/_authenticated/productCatalog/'
      path: '/productCatalog'
      fullPath: '/productCatalog'
      preLoaderRoute: typeof AuthenticatedProductCatalogIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/store/': {
      id: '/_authenticated/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/pages/about-us/': {
      id: '/pages/about-us/'
      path: '/pages/about-us'
      fullPath: '/pages/about-us'
      preLoaderRoute: typeof PagesAboutUsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/careers/': {
      id: '/pages/careers/'
      path: '/pages/careers'
      fullPath: '/pages/careers'
      preLoaderRoute: typeof PagesCareersIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/creating-products/': {
      id: '/pages/creating-products/'
      path: '/pages/creating-products'
      fullPath: '/pages/creating-products'
      preLoaderRoute: typeof PagesCreatingProductsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/creator-store/': {
      id: '/pages/creator-store/'
      path: '/pages/creator-store'
      fullPath: '/pages/creator-store'
      preLoaderRoute: typeof PagesCreatorStoreIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/for-creators/': {
      id: '/pages/for-creators/'
      path: '/pages/for-creators'
      fullPath: '/pages/for-creators'
      preLoaderRoute: typeof PagesForCreatorsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/fulfillment-page/': {
      id: '/pages/fulfillment-page/'
      path: '/pages/fulfillment-page'
      fullPath: '/pages/fulfillment-page'
      preLoaderRoute: typeof PagesFulfillmentPageIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/getting-started/': {
      id: '/pages/getting-started/'
      path: '/pages/getting-started'
      fullPath: '/pages/getting-started'
      preLoaderRoute: typeof PagesGettingStartedIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/make_your_brand/': {
      id: '/pages/make_your_brand/'
      path: '/pages/make_your_brand'
      fullPath: '/pages/make_your_brand'
      preLoaderRoute: typeof PagesMakeyourbrandIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/privacy/': {
      id: '/pages/privacy/'
      path: '/pages/privacy'
      fullPath: '/pages/privacy'
      preLoaderRoute: typeof PagesPrivacyIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/productCatalog/products/$id': {
      id: '/_authenticated/productCatalog/products/$id'
      path: '/productCatalog/products/$id'
      fullPath: '/productCatalog/products/$id'
      preLoaderRoute: typeof AuthenticatedProductCatalogProductsIdLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/store/billing-history/': {
      id: '/_authenticated/store/billing-history/'
      path: '/store/billing-history'
      fullPath: '/store/billing-history'
      preLoaderRoute: typeof AuthenticatedStoreBillingHistoryIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/productCatalog/products/': {
      id: '/_authenticated/productCatalog/products/'
      path: '/productCatalog/products'
      fullPath: '/productCatalog/products'
      preLoaderRoute: typeof AuthenticatedProductCatalogProductsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/store/collections/': {
      id: '/_authenticated/store/collections/'
      path: '/'
      fullPath: '/store/collections/'
      preLoaderRoute: typeof AuthenticatedStoreCollectionsIndexLazyImport
      parentRoute: typeof AuthenticatedStoreCollectionsRouteImport
    }
    '/_authenticated/store/editor/': {
      id: '/_authenticated/store/editor/'
      path: '/'
      fullPath: '/store/editor/'
      preLoaderRoute: typeof AuthenticatedStoreEditorIndexLazyImport
      parentRoute: typeof AuthenticatedStoreEditorRouteImport
    }
    '/_authenticated/store/membership/': {
      id: '/_authenticated/store/membership/'
      path: '/'
      fullPath: '/store/membership/'
      preLoaderRoute: typeof AuthenticatedStoreMembershipIndexLazyImport
      parentRoute: typeof AuthenticatedStoreMembershipRouteImport
    }
    '/_authenticated/productCatalog/category/$slug/$id': {
      id: '/_authenticated/productCatalog/category/$slug/$id'
      path: '/productCatalog/category/$slug/$id'
      fullPath: '/productCatalog/category/$slug/$id'
      preLoaderRoute: typeof AuthenticatedProductCatalogCategorySlugIdLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/productCatalog/category/$slug/': {
      id: '/_authenticated/productCatalog/category/$slug/'
      path: '/productCatalog/category/$slug'
      fullPath: '/productCatalog/category/$slug'
      preLoaderRoute: typeof AuthenticatedProductCatalogCategorySlugIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedStoreCollectionsRouteRouteChildren {
  AuthenticatedStoreCollectionsIndexLazyRoute: typeof AuthenticatedStoreCollectionsIndexLazyRoute
}

const AuthenticatedStoreCollectionsRouteRouteChildren: AuthenticatedStoreCollectionsRouteRouteChildren =
  {
    AuthenticatedStoreCollectionsIndexLazyRoute:
      AuthenticatedStoreCollectionsIndexLazyRoute,
  }

const AuthenticatedStoreCollectionsRouteRouteWithChildren =
  AuthenticatedStoreCollectionsRouteRoute._addFileChildren(
    AuthenticatedStoreCollectionsRouteRouteChildren,
  )

interface AuthenticatedStoreEditorRouteRouteChildren {
  AuthenticatedStoreEditorIndexLazyRoute: typeof AuthenticatedStoreEditorIndexLazyRoute
}

const AuthenticatedStoreEditorRouteRouteChildren: AuthenticatedStoreEditorRouteRouteChildren =
  {
    AuthenticatedStoreEditorIndexLazyRoute:
      AuthenticatedStoreEditorIndexLazyRoute,
  }

const AuthenticatedStoreEditorRouteRouteWithChildren =
  AuthenticatedStoreEditorRouteRoute._addFileChildren(
    AuthenticatedStoreEditorRouteRouteChildren,
  )

interface AuthenticatedStoreMembershipRouteRouteChildren {
  AuthenticatedStoreMembershipIndexLazyRoute: typeof AuthenticatedStoreMembershipIndexLazyRoute
}

const AuthenticatedStoreMembershipRouteRouteChildren: AuthenticatedStoreMembershipRouteRouteChildren =
  {
    AuthenticatedStoreMembershipIndexLazyRoute:
      AuthenticatedStoreMembershipIndexLazyRoute,
  }

const AuthenticatedStoreMembershipRouteRouteWithChildren =
  AuthenticatedStoreMembershipRouteRoute._addFileChildren(
    AuthenticatedStoreMembershipRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStoreCollectionsRouteRoute: typeof AuthenticatedStoreCollectionsRouteRouteWithChildren
  AuthenticatedStoreEditorRouteRoute: typeof AuthenticatedStoreEditorRouteRouteWithChildren
  AuthenticatedStoreMembershipRouteRoute: typeof AuthenticatedStoreMembershipRouteRouteWithChildren
  AuthenticatedDesignerIdLazyRoute: typeof AuthenticatedDesignerIdLazyRoute
  AuthenticatedDesignerCreateLazyRoute: typeof AuthenticatedDesignerCreateLazyRoute
  AuthenticatedOrdersIdLazyRoute: typeof AuthenticatedOrdersIdLazyRoute
  AuthenticatedProductCatalogIdLazyRoute: typeof AuthenticatedProductCatalogIdLazyRoute
  AuthenticatedProductsIdLazyRoute: typeof AuthenticatedProductsIdLazyRoute
  AuthenticatedProductsCreateproductLazyRoute: typeof AuthenticatedProductsCreateproductLazyRoute
  AuthenticatedChatsIndexLazyRoute: typeof AuthenticatedChatsIndexLazyRoute
  AuthenticatedCustomersIndexLazyRoute: typeof AuthenticatedCustomersIndexLazyRoute
  AuthenticatedDashboardIndexLazyRoute: typeof AuthenticatedDashboardIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedOrdersIndexLazyRoute: typeof AuthenticatedOrdersIndexLazyRoute
  AuthenticatedPayoutsIndexLazyRoute: typeof AuthenticatedPayoutsIndexLazyRoute
  AuthenticatedProductCatalogIndexLazyRoute: typeof AuthenticatedProductCatalogIndexLazyRoute
  AuthenticatedProductsIndexLazyRoute: typeof AuthenticatedProductsIndexLazyRoute
  AuthenticatedStoreIndexLazyRoute: typeof AuthenticatedStoreIndexLazyRoute
  AuthenticatedProductCatalogProductsIdLazyRoute: typeof AuthenticatedProductCatalogProductsIdLazyRoute
  AuthenticatedStoreBillingHistoryIndexRoute: typeof AuthenticatedStoreBillingHistoryIndexRoute
  AuthenticatedProductCatalogProductsIndexLazyRoute: typeof AuthenticatedProductCatalogProductsIndexLazyRoute
  AuthenticatedProductCatalogCategorySlugIdLazyRoute: typeof AuthenticatedProductCatalogCategorySlugIdLazyRoute
  AuthenticatedProductCatalogCategorySlugIndexLazyRoute: typeof AuthenticatedProductCatalogCategorySlugIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStoreCollectionsRouteRoute:
    AuthenticatedStoreCollectionsRouteRouteWithChildren,
  AuthenticatedStoreEditorRouteRoute:
    AuthenticatedStoreEditorRouteRouteWithChildren,
  AuthenticatedStoreMembershipRouteRoute:
    AuthenticatedStoreMembershipRouteRouteWithChildren,
  AuthenticatedDesignerIdLazyRoute: AuthenticatedDesignerIdLazyRoute,
  AuthenticatedDesignerCreateLazyRoute: AuthenticatedDesignerCreateLazyRoute,
  AuthenticatedOrdersIdLazyRoute: AuthenticatedOrdersIdLazyRoute,
  AuthenticatedProductCatalogIdLazyRoute:
    AuthenticatedProductCatalogIdLazyRoute,
  AuthenticatedProductsIdLazyRoute: AuthenticatedProductsIdLazyRoute,
  AuthenticatedProductsCreateproductLazyRoute:
    AuthenticatedProductsCreateproductLazyRoute,
  AuthenticatedChatsIndexLazyRoute: AuthenticatedChatsIndexLazyRoute,
  AuthenticatedCustomersIndexLazyRoute: AuthenticatedCustomersIndexLazyRoute,
  AuthenticatedDashboardIndexLazyRoute: AuthenticatedDashboardIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedOrdersIndexLazyRoute: AuthenticatedOrdersIndexLazyRoute,
  AuthenticatedPayoutsIndexLazyRoute: AuthenticatedPayoutsIndexLazyRoute,
  AuthenticatedProductCatalogIndexLazyRoute:
    AuthenticatedProductCatalogIndexLazyRoute,
  AuthenticatedProductsIndexLazyRoute: AuthenticatedProductsIndexLazyRoute,
  AuthenticatedStoreIndexLazyRoute: AuthenticatedStoreIndexLazyRoute,
  AuthenticatedProductCatalogProductsIdLazyRoute:
    AuthenticatedProductCatalogProductsIdLazyRoute,
  AuthenticatedStoreBillingHistoryIndexRoute:
    AuthenticatedStoreBillingHistoryIndexRoute,
  AuthenticatedProductCatalogProductsIndexLazyRoute:
    AuthenticatedProductCatalogProductsIndexLazyRoute,
  AuthenticatedProductCatalogCategorySlugIdLazyRoute:
    AuthenticatedProductCatalogCategorySlugIdLazyRoute,
  AuthenticatedProductCatalogCategorySlugIndexLazyRoute:
    AuthenticatedProductCatalogCategorySlugIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/homepage': typeof authHomepageLazyRoute
  '/onboarding': typeof authOnboardingLazyRoute
  '/profile': typeof authProfileLazyRoute
  '/reset-password': typeof authResetPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth-callback': typeof AuthCallbackIndexLazyRoute
  '/store/collections': typeof AuthenticatedStoreCollectionsRouteRouteWithChildren
  '/store/editor': typeof AuthenticatedStoreEditorRouteRouteWithChildren
  '/store/membership': typeof AuthenticatedStoreMembershipRouteRouteWithChildren
  '/designer/$id': typeof AuthenticatedDesignerIdLazyRoute
  '/designer/create': typeof AuthenticatedDesignerCreateLazyRoute
  '/orders/$id': typeof AuthenticatedOrdersIdLazyRoute
  '/productCatalog/$id': typeof AuthenticatedProductCatalogIdLazyRoute
  '/products/$id': typeof AuthenticatedProductsIdLazyRoute
  '/products/createproduct': typeof AuthenticatedProductsCreateproductLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/customers': typeof AuthenticatedCustomersIndexLazyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/orders': typeof AuthenticatedOrdersIndexLazyRoute
  '/payouts': typeof AuthenticatedPayoutsIndexLazyRoute
  '/productCatalog': typeof AuthenticatedProductCatalogIndexLazyRoute
  '/products': typeof AuthenticatedProductsIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/store': typeof AuthenticatedStoreIndexLazyRoute
  '/pages/about-us': typeof PagesAboutUsIndexLazyRoute
  '/pages/careers': typeof PagesCareersIndexLazyRoute
  '/pages/creating-products': typeof PagesCreatingProductsIndexLazyRoute
  '/pages/creator-store': typeof PagesCreatorStoreIndexLazyRoute
  '/pages/for-creators': typeof PagesForCreatorsIndexLazyRoute
  '/pages/fulfillment-page': typeof PagesFulfillmentPageIndexLazyRoute
  '/pages/getting-started': typeof PagesGettingStartedIndexLazyRoute
  '/pages/make_your_brand': typeof PagesMakeyourbrandIndexLazyRoute
  '/pages/privacy': typeof PagesPrivacyIndexLazyRoute
  '/productCatalog/products/$id': typeof AuthenticatedProductCatalogProductsIdLazyRoute
  '/store/billing-history': typeof AuthenticatedStoreBillingHistoryIndexRoute
  '/productCatalog/products': typeof AuthenticatedProductCatalogProductsIndexLazyRoute
  '/store/collections/': typeof AuthenticatedStoreCollectionsIndexLazyRoute
  '/store/editor/': typeof AuthenticatedStoreEditorIndexLazyRoute
  '/store/membership/': typeof AuthenticatedStoreMembershipIndexLazyRoute
  '/productCatalog/category/$slug/$id': typeof AuthenticatedProductCatalogCategorySlugIdLazyRoute
  '/productCatalog/category/$slug': typeof AuthenticatedProductCatalogCategorySlugIndexLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/homepage': typeof authHomepageLazyRoute
  '/onboarding': typeof authOnboardingLazyRoute
  '/profile': typeof authProfileLazyRoute
  '/reset-password': typeof authResetPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth-callback': typeof AuthCallbackIndexLazyRoute
  '/designer/$id': typeof AuthenticatedDesignerIdLazyRoute
  '/designer/create': typeof AuthenticatedDesignerCreateLazyRoute
  '/orders/$id': typeof AuthenticatedOrdersIdLazyRoute
  '/productCatalog/$id': typeof AuthenticatedProductCatalogIdLazyRoute
  '/products/$id': typeof AuthenticatedProductsIdLazyRoute
  '/products/createproduct': typeof AuthenticatedProductsCreateproductLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/customers': typeof AuthenticatedCustomersIndexLazyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/orders': typeof AuthenticatedOrdersIndexLazyRoute
  '/payouts': typeof AuthenticatedPayoutsIndexLazyRoute
  '/productCatalog': typeof AuthenticatedProductCatalogIndexLazyRoute
  '/products': typeof AuthenticatedProductsIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/store': typeof AuthenticatedStoreIndexLazyRoute
  '/pages/about-us': typeof PagesAboutUsIndexLazyRoute
  '/pages/careers': typeof PagesCareersIndexLazyRoute
  '/pages/creating-products': typeof PagesCreatingProductsIndexLazyRoute
  '/pages/creator-store': typeof PagesCreatorStoreIndexLazyRoute
  '/pages/for-creators': typeof PagesForCreatorsIndexLazyRoute
  '/pages/fulfillment-page': typeof PagesFulfillmentPageIndexLazyRoute
  '/pages/getting-started': typeof PagesGettingStartedIndexLazyRoute
  '/pages/make_your_brand': typeof PagesMakeyourbrandIndexLazyRoute
  '/pages/privacy': typeof PagesPrivacyIndexLazyRoute
  '/productCatalog/products/$id': typeof AuthenticatedProductCatalogProductsIdLazyRoute
  '/store/billing-history': typeof AuthenticatedStoreBillingHistoryIndexRoute
  '/productCatalog/products': typeof AuthenticatedProductCatalogProductsIndexLazyRoute
  '/store/collections': typeof AuthenticatedStoreCollectionsIndexLazyRoute
  '/store/editor': typeof AuthenticatedStoreEditorIndexLazyRoute
  '/store/membership': typeof AuthenticatedStoreMembershipIndexLazyRoute
  '/productCatalog/category/$slug/$id': typeof AuthenticatedProductCatalogCategorySlugIdLazyRoute
  '/productCatalog/category/$slug': typeof AuthenticatedProductCatalogCategorySlugIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/homepage': typeof authHomepageLazyRoute
  '/(auth)/onboarding': typeof authOnboardingLazyRoute
  '/(auth)/profile': typeof authProfileLazyRoute
  '/(auth)/reset-password': typeof authResetPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth-callback/': typeof AuthCallbackIndexLazyRoute
  '/_authenticated/store/collections': typeof AuthenticatedStoreCollectionsRouteRouteWithChildren
  '/_authenticated/store/editor': typeof AuthenticatedStoreEditorRouteRouteWithChildren
  '/_authenticated/store/membership': typeof AuthenticatedStoreMembershipRouteRouteWithChildren
  '/_authenticated/designer/$id': typeof AuthenticatedDesignerIdLazyRoute
  '/_authenticated/designer/create': typeof AuthenticatedDesignerCreateLazyRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdLazyRoute
  '/_authenticated/productCatalog/$id': typeof AuthenticatedProductCatalogIdLazyRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdLazyRoute
  '/_authenticated/products/createproduct': typeof AuthenticatedProductsCreateproductLazyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexLazyRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexLazyRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexLazyRoute
  '/_authenticated/payouts/': typeof AuthenticatedPayoutsIndexLazyRoute
  '/_authenticated/productCatalog/': typeof AuthenticatedProductCatalogIndexLazyRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/store/': typeof AuthenticatedStoreIndexLazyRoute
  '/pages/about-us/': typeof PagesAboutUsIndexLazyRoute
  '/pages/careers/': typeof PagesCareersIndexLazyRoute
  '/pages/creating-products/': typeof PagesCreatingProductsIndexLazyRoute
  '/pages/creator-store/': typeof PagesCreatorStoreIndexLazyRoute
  '/pages/for-creators/': typeof PagesForCreatorsIndexLazyRoute
  '/pages/fulfillment-page/': typeof PagesFulfillmentPageIndexLazyRoute
  '/pages/getting-started/': typeof PagesGettingStartedIndexLazyRoute
  '/pages/make_your_brand/': typeof PagesMakeyourbrandIndexLazyRoute
  '/pages/privacy/': typeof PagesPrivacyIndexLazyRoute
  '/_authenticated/productCatalog/products/$id': typeof AuthenticatedProductCatalogProductsIdLazyRoute
  '/_authenticated/store/billing-history/': typeof AuthenticatedStoreBillingHistoryIndexRoute
  '/_authenticated/productCatalog/products/': typeof AuthenticatedProductCatalogProductsIndexLazyRoute
  '/_authenticated/store/collections/': typeof AuthenticatedStoreCollectionsIndexLazyRoute
  '/_authenticated/store/editor/': typeof AuthenticatedStoreEditorIndexLazyRoute
  '/_authenticated/store/membership/': typeof AuthenticatedStoreMembershipIndexLazyRoute
  '/_authenticated/productCatalog/category/$slug/$id': typeof AuthenticatedProductCatalogCategorySlugIdLazyRoute
  '/_authenticated/productCatalog/category/$slug/': typeof AuthenticatedProductCatalogCategorySlugIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/homepage'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/auth-callback'
    | '/store/collections'
    | '/store/editor'
    | '/store/membership'
    | '/designer/$id'
    | '/designer/create'
    | '/orders/$id'
    | '/productCatalog/$id'
    | '/products/$id'
    | '/products/createproduct'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/chats'
    | '/customers'
    | '/dashboard'
    | '/help-center'
    | '/orders'
    | '/payouts'
    | '/productCatalog'
    | '/products'
    | '/settings/'
    | '/store'
    | '/pages/about-us'
    | '/pages/careers'
    | '/pages/creating-products'
    | '/pages/creator-store'
    | '/pages/for-creators'
    | '/pages/fulfillment-page'
    | '/pages/getting-started'
    | '/pages/make_your_brand'
    | '/pages/privacy'
    | '/productCatalog/products/$id'
    | '/store/billing-history'
    | '/productCatalog/products'
    | '/store/collections/'
    | '/store/editor/'
    | '/store/membership/'
    | '/productCatalog/category/$slug/$id'
    | '/productCatalog/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/homepage'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/auth-callback'
    | '/designer/$id'
    | '/designer/create'
    | '/orders/$id'
    | '/productCatalog/$id'
    | '/products/$id'
    | '/products/createproduct'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/chats'
    | '/customers'
    | '/dashboard'
    | '/help-center'
    | '/orders'
    | '/payouts'
    | '/productCatalog'
    | '/products'
    | '/settings'
    | '/store'
    | '/pages/about-us'
    | '/pages/careers'
    | '/pages/creating-products'
    | '/pages/creator-store'
    | '/pages/for-creators'
    | '/pages/fulfillment-page'
    | '/pages/getting-started'
    | '/pages/make_your_brand'
    | '/pages/privacy'
    | '/productCatalog/products/$id'
    | '/store/billing-history'
    | '/productCatalog/products'
    | '/store/collections'
    | '/store/editor'
    | '/store/membership'
    | '/productCatalog/category/$slug/$id'
    | '/productCatalog/category/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/homepage'
    | '/(auth)/onboarding'
    | '/(auth)/profile'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/auth-callback/'
    | '/_authenticated/store/collections'
    | '/_authenticated/store/editor'
    | '/_authenticated/store/membership'
    | '/_authenticated/designer/$id'
    | '/_authenticated/designer/create'
    | '/_authenticated/orders/$id'
    | '/_authenticated/productCatalog/$id'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/createproduct'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/chats/'
    | '/_authenticated/customers/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/help-center/'
    | '/_authenticated/orders/'
    | '/_authenticated/payouts/'
    | '/_authenticated/productCatalog/'
    | '/_authenticated/products/'
    | '/_authenticated/settings/'
    | '/_authenticated/store/'
    | '/pages/about-us/'
    | '/pages/careers/'
    | '/pages/creating-products/'
    | '/pages/creator-store/'
    | '/pages/for-creators/'
    | '/pages/fulfillment-page/'
    | '/pages/getting-started/'
    | '/pages/make_your_brand/'
    | '/pages/privacy/'
    | '/_authenticated/productCatalog/products/$id'
    | '/_authenticated/store/billing-history/'
    | '/_authenticated/productCatalog/products/'
    | '/_authenticated/store/collections/'
    | '/_authenticated/store/editor/'
    | '/_authenticated/store/membership/'
    | '/_authenticated/productCatalog/category/$slug/$id'
    | '/_authenticated/productCatalog/category/$slug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authHomepageLazyRoute: typeof authHomepageLazyRoute
  authOnboardingLazyRoute: typeof authOnboardingLazyRoute
  authProfileLazyRoute: typeof authProfileLazyRoute
  authResetPasswordLazyRoute: typeof authResetPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  AuthCallbackIndexLazyRoute: typeof AuthCallbackIndexLazyRoute
  PagesAboutUsIndexLazyRoute: typeof PagesAboutUsIndexLazyRoute
  PagesCareersIndexLazyRoute: typeof PagesCareersIndexLazyRoute
  PagesCreatingProductsIndexLazyRoute: typeof PagesCreatingProductsIndexLazyRoute
  PagesCreatorStoreIndexLazyRoute: typeof PagesCreatorStoreIndexLazyRoute
  PagesForCreatorsIndexLazyRoute: typeof PagesForCreatorsIndexLazyRoute
  PagesFulfillmentPageIndexLazyRoute: typeof PagesFulfillmentPageIndexLazyRoute
  PagesGettingStartedIndexLazyRoute: typeof PagesGettingStartedIndexLazyRoute
  PagesMakeyourbrandIndexLazyRoute: typeof PagesMakeyourbrandIndexLazyRoute
  PagesPrivacyIndexLazyRoute: typeof PagesPrivacyIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authHomepageLazyRoute: authHomepageLazyRoute,
  authOnboardingLazyRoute: authOnboardingLazyRoute,
  authProfileLazyRoute: authProfileLazyRoute,
  authResetPasswordLazyRoute: authResetPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  AuthCallbackIndexLazyRoute: AuthCallbackIndexLazyRoute,
  PagesAboutUsIndexLazyRoute: PagesAboutUsIndexLazyRoute,
  PagesCareersIndexLazyRoute: PagesCareersIndexLazyRoute,
  PagesCreatingProductsIndexLazyRoute: PagesCreatingProductsIndexLazyRoute,
  PagesCreatorStoreIndexLazyRoute: PagesCreatorStoreIndexLazyRoute,
  PagesForCreatorsIndexLazyRoute: PagesForCreatorsIndexLazyRoute,
  PagesFulfillmentPageIndexLazyRoute: PagesFulfillmentPageIndexLazyRoute,
  PagesGettingStartedIndexLazyRoute: PagesGettingStartedIndexLazyRoute,
  PagesMakeyourbrandIndexLazyRoute: PagesMakeyourbrandIndexLazyRoute,
  PagesPrivacyIndexLazyRoute: PagesPrivacyIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/homepage",
        "/(auth)/onboarding",
        "/(auth)/profile",
        "/(auth)/reset-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/auth-callback/",
        "/pages/about-us/",
        "/pages/careers/",
        "/pages/creating-products/",
        "/pages/creator-store/",
        "/pages/for-creators/",
        "/pages/fulfillment-page/",
        "/pages/getting-started/",
        "/pages/make_your_brand/",
        "/pages/privacy/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/store/collections",
        "/_authenticated/store/editor",
        "/_authenticated/store/membership",
        "/_authenticated/designer/$id",
        "/_authenticated/designer/create",
        "/_authenticated/orders/$id",
        "/_authenticated/productCatalog/$id",
        "/_authenticated/products/$id",
        "/_authenticated/products/createproduct",
        "/_authenticated/chats/",
        "/_authenticated/customers/",
        "/_authenticated/dashboard/",
        "/_authenticated/help-center/",
        "/_authenticated/orders/",
        "/_authenticated/payouts/",
        "/_authenticated/productCatalog/",
        "/_authenticated/products/",
        "/_authenticated/store/",
        "/_authenticated/productCatalog/products/$id",
        "/_authenticated/store/billing-history/",
        "/_authenticated/productCatalog/products/",
        "/_authenticated/productCatalog/category/$slug/$id",
        "/_authenticated/productCatalog/category/$slug/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/homepage": {
      "filePath": "(auth)/homepage.lazy.tsx"
    },
    "/(auth)/onboarding": {
      "filePath": "(auth)/onboarding.lazy.tsx"
    },
    "/(auth)/profile": {
      "filePath": "(auth)/profile.lazy.tsx"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/auth-callback/": {
      "filePath": "auth-callback/index.lazy.tsx"
    },
    "/_authenticated/store/collections": {
      "filePath": "_authenticated/store/collections/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/store/collections/"
      ]
    },
    "/_authenticated/store/editor": {
      "filePath": "_authenticated/store/editor/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/store/editor/"
      ]
    },
    "/_authenticated/store/membership": {
      "filePath": "_authenticated/store/membership/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/store/membership/"
      ]
    },
    "/_authenticated/designer/$id": {
      "filePath": "_authenticated/designer/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/designer/create": {
      "filePath": "_authenticated/designer/create.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orders/$id": {
      "filePath": "_authenticated/orders/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/productCatalog/$id": {
      "filePath": "_authenticated/productCatalog/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products/$id": {
      "filePath": "_authenticated/products/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products/createproduct": {
      "filePath": "_authenticated/products/createproduct.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/": {
      "filePath": "_authenticated/customers/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orders/": {
      "filePath": "_authenticated/orders/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/payouts/": {
      "filePath": "_authenticated/payouts/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/productCatalog/": {
      "filePath": "_authenticated/productCatalog/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/products/": {
      "filePath": "_authenticated/products/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/store/": {
      "filePath": "_authenticated/store/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/pages/about-us/": {
      "filePath": "pages/about-us/index.lazy.tsx"
    },
    "/pages/careers/": {
      "filePath": "pages/careers/index.lazy.tsx"
    },
    "/pages/creating-products/": {
      "filePath": "pages/creating-products/index.lazy.tsx"
    },
    "/pages/creator-store/": {
      "filePath": "pages/creator-store/index.lazy.tsx"
    },
    "/pages/for-creators/": {
      "filePath": "pages/for-creators/index.lazy.tsx"
    },
    "/pages/fulfillment-page/": {
      "filePath": "pages/fulfillment-page/index.lazy.tsx"
    },
    "/pages/getting-started/": {
      "filePath": "pages/getting-started/index.lazy.tsx"
    },
    "/pages/make_your_brand/": {
      "filePath": "pages/make_your_brand/index.lazy.tsx"
    },
    "/pages/privacy/": {
      "filePath": "pages/privacy/index.lazy.tsx"
    },
    "/_authenticated/productCatalog/products/$id": {
      "filePath": "_authenticated/productCatalog/products/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/store/billing-history/": {
      "filePath": "_authenticated/store/billing-history/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/productCatalog/products/": {
      "filePath": "_authenticated/productCatalog/products/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/store/collections/": {
      "filePath": "_authenticated/store/collections/index.lazy.tsx",
      "parent": "/_authenticated/store/collections"
    },
    "/_authenticated/store/editor/": {
      "filePath": "_authenticated/store/editor/index.lazy.tsx",
      "parent": "/_authenticated/store/editor"
    },
    "/_authenticated/store/membership/": {
      "filePath": "_authenticated/store/membership/index.lazy.tsx",
      "parent": "/_authenticated/store/membership"
    },
    "/_authenticated/productCatalog/category/$slug/$id": {
      "filePath": "_authenticated/productCatalog/category/$slug/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/productCatalog/category/$slug/": {
      "filePath": "_authenticated/productCatalog/category/$slug/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
