/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    'blank-products': BlankProduct;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'blank-products': BlankProductsSelect<false> | BlankProductsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  /**
   * Mark this category as featured to display it on the homepage of catalog
   */
  featuredCategory?: boolean | null;
  /**
   * Mark this category to show on the studio navigation
   */
  StudioCategory?: boolean | null;
  products?: (number | BlankProduct)[] | null;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Professional print-on-demand with advanced masking & surface mapping
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blank-products".
 */
export interface BlankProduct {
  id: number;
  /**
   * Product name as displayed to customers
   */
  name: string;
  /**
   * URL-friendly version of the name
   */
  slug?: string | null;
  status: 'active' | 'draft' | 'discontinued' | 'out_of_stock' | 'coming_soon';
  productType:
    | 'apparel_tshirt'
    | 'apparel_hoodie'
    | 'apparel_sweatshirt'
    | 'apparel_tank'
    | 'apparel_longsleeve'
    | 'apparel_hat'
    | 'apparel_beanie'
    | 'drinkware_mug'
    | 'drinkware_bottle'
    | 'drinkware_tumbler'
    | 'print_poster'
    | 'print_canvas'
    | 'print_business_card'
    | 'print_sticker'
    | 'accessories_phone_case'
    | 'accessories_tote_bag'
    | 'accessories_backpack'
    | 'home_pillow'
    | 'home_blanket'
    | 'home_towel'
    | 'other';
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  brand: string;
  brandSku?: string | null;
  sku: string;
  'Manufacturer sku'?: string | null;
  vendorInfo?: {
    supplier?: ('printful' | 'printify' | 'gooten' | 'qikink' | 'local' | 'direct' | 'other') | null;
    supplierProductId?: string | null;
    countryOrigin?: string | null;
  };
  sourcing?: {
    minOrderQty?: number | null;
    leadTimeDays?: string | null;
    shipTimeDays?: string | null;
    rushAvailable?: boolean | null;
    rushLeadTimeDays?: number | null;
  };
  cost: number;
  'GST Cost'?: number | null;
  pricing?: {
    markupType?: ('percentage' | 'fixed' | 'tiered') | null;
    markupValue?: number | null;
    suggestedRetail?: number | null;
  };
  pricingTiers?:
    | {
        minQuantity: number;
        maxQuantity?: number | null;
        markupPercentage: number;
        id?: string | null;
      }[]
    | null;
  additionalCosts?: {
    printingCostPerArea?: number | null;
    printingGST?: number | null;
    setupFee?: number | null;
    rushSurcharge?: number | null;
  };
  description?: string | null;
  features?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  HSNCode?: string | null;
  materials?: {
    primary?: string | null;
    weight?: string | null;
    construction?: string | null;
    finish?: string | null;
    /**
     * Material type for accurate surface rendering
     */
    efabType?:
      | (
          | 'cotton'
          | 'polyester'
          | 'blend'
          | 'canvas'
          | 'leather'
          | 'denim'
          | 'fleece'
          | 'jersey'
          | 'mesh'
          | 'vinyl'
          | 'paper'
          | 'ceramic'
          | 'metal'
          | 'plastic'
        )
      | null;
    /**
     * Fabric weight in GSM (grams per square meter)
     */
    fabricWeight?: number | null;
    surfaceTexture?: ('smooth' | 'textured' | 'rough' | 'glossy' | 'matte' | 'satin' | 'brushed') | null;
    /**
     * Fabric stretch factor (0 = no stretch, 1 = very stretchy)
     */
    stretchability?: number | null;
    /**
     * Fabric transparency level (0 = opaque, 1 = transparent)
     */
    transparency?: number | null;
    /**
     * Surface reflectivity for lighting calculations
     */
    reflectivity?: number | null;
  };
  careInstructions?:
    | {
        instruction: string;
        icon?:
          | (
              | 'wash_cold'
              | 'wash_warm'
              | 'hand_wash'
              | 'no_wash'
              | 'dry_low'
              | 'hang_dry'
              | 'no_dry'
              | 'iron_low'
              | 'no_iron'
              | 'no_bleach'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  physicalDimensions?: {
    widthInches?: number | null;
    heightInches?: number | null;
    depthInches?: number | null;
    diameter?: number | null;
    units?: ('inches' | 'cm' | 'mm') | null;
  };
  shippingInfo: {
    weight: number;
    shippingDimensions?: string | null;
    shippingCharges?: string | null;
    shippingLocationID?: string | null;
    shippingProfileID?: string | null;
    packageType?: ('poly_mailer' | 'box' | 'envelope' | 'tube' | 'custom') | null;
  };
  colorOptions?:
    | {
        colorName: string;
        colorHex: string;
        colorSku?: string | null;
        isPrimary?: boolean | null;
        fabricInteraction?: {
          /**
           * How much ink the fabric color absorbs (affects final appearance)
           */
          absorptionRate?: number | null;
          blendMode?: ('normal' | 'multiply' | 'screen' | 'overlay' | 'soft_light') | null;
          colorShift?: {
            hueShift?: number | null;
            saturationShift?: number | null;
            lightnessShift?: number | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  color_Images?: boolean | null;
  sizeOptions?:
    | {
        sizeName: string;
        sizeSku?: string | null;
        ExtraCost?: string | null;
        sizeDescription?: string | null;
        dimensions?: {
          width?: number | null;
          height?: number | null;
        };
        id?: string | null;
      }[]
    | null;
  size_Images?: boolean | null;
  sizeChart?: (number | null) | Media;
  sizeChartHtml?: string | null;
  surfConf: {
    No_Mockup_Compatible?: boolean | null;
    renderType: 'flat' | 'cylindrical' | 'conical' | 'spherical' | 'complex_3d' | 'apparel_body' | 'sleeve_wrap';
    surfProp?: {
      wrapAngle?: number | null;
      curveInten?: number | null;
      designRatio?: {
        widthRatio?: number | null;
        heightRatio?: number | null;
      };
    };
    blendSet?: {
      defaultBlendMode?: ('normal' | 'multiply' | 'screen' | 'overlay' | 'soft_light') | null;
      defaultOpacity?: number | null;
      preserveColors?: boolean | null;
    };
  };
  advanSurfMap?: {
    curvProf?: ('linear' | 'smooth' | 'elastic' | 'ease_in' | 'ease_out' | 'custom') | null;
    /**
     * Barrel distortion coefficient
     */
    barrelDist?: number | null;
    pincushiDistor?: number | null;
    perspDis?: number | null;
    hasSeams?: boolean | null;
  };
  seamPositions?:
    | {
        seamTypes?: ('side' | 'shoulder' | 'sleeve' | 'hem' | 'custom') | null;
        positionX?: number | null;
        positionY?: number | null;
        width?: number | null;
        seamEffect?: ('indent' | 'raised' | 'flat' | 'shadow') | null;
        id?: string | null;
      }[]
    | null;
  lightingConfiguration?: {
    /**
     * Light direction in degrees (0 = top, 90 = right)
     */
    lightDirection?: number | null;
    lightIntensity?: number | null;
    ambientLight?: number | null;
    shadowIntensity?: number | null;
  };
  printT?:
    | {
        id?: string | null;
        technologyName: 'dtg' | 'dtf' | 'screen' | 'sublimation' | 'embroidery' | 'vinyl' | 'digital' | 'uv' | 'laser';
        printingConstraints?: {
          dpiRequirements?: {
            minimum?: number | null;
            recommended?: number | null;
            maximum?: number | null;
          };
          sizeLimits?: {
            minWidthInch?: number | null;
            minHeightInch?: number | null;
            maxWidthInch?: number | null;
            maxHeightInch?: number | null;
          };
          colorLimits?: {
            maxColors?: number | null;
            supportsFullColor?: boolean | null;
          };
          printBleeds?: {
            /**
             * Bleed margin in millimeters
             */
            bleedMargin?: number | null;
            /**
             * Safety margin in millimeters
             */
            safetyMargin?: number | null;
            /**
             * Trim tolerance in millimeters
             */
            trimTolerance?: number | null;
          };
        };
        mockupPhotos?:
          | {
              title?: string | null;
              photo: number | Media;
              mocwidthpx?: number | null;
              mochigtpx?: number | null;
              tmbwidthpx?: number | null;
              tmbhigtpx?: number | null;
              viewAngle?:
                | (
                    | 'front'
                    | 'back'
                    | 'left'
                    | 'right'
                    | 'three_quarter_front_left'
                    | 'three_quarter_front_right'
                    | 'top'
                    | 'bottom'
                    | 'lifestyle'
                    | 'detail'
                    | 'flat'
                  )
                | null;
              mockupType?: ('studio' | 'lifestyle' | 'model' | 'flat_lay') | null;
              photoColor: string;
              photoSize?: string | null;
              /**
               * Displacement maps for curved surfaces (mugs, bottles, curved products)
               */
              dispMaps?:
                | {
                    /**
                     * PNG displacement map (512x512 recommended)
                     */
                    dispImg: number | Media;
                    dsrface?: ('cylindrical' | 'conical' | 'spherical') | null;
                    /**
                     * Displacement intensity (0.1 = subtle, 1.5 = strong)
                     */
                    disint?: number | null;
                    /**
                     * Which area this applies to (must match visibleArea areaName)
                     */
                    disarea: string;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Alpha masks to define precise printable areas (white = printable, black = non-printable)
               */
              alpMasks?:
                | {
                    /**
                     * PNG with alpha channel (same dimensions as mockup photo)
                     */
                    maskImg: number | Media;
                    /**
                     * Which area this mask applies to (must match visibleArea areaName)
                     */
                    alfarea: string;
                    alfmask?: ('alpha' | 'luminance' | 'red_channel') | null;
                    /**
                     * Edge softness in pixels (0 = sharp, 5 = soft)
                     */
                    featherEdge?: number | null;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Lighting and shadow overlays for realistic mockup effects
               */
              light?:
                | {
                    /**
                     * PNG lighting/shadow overlay (same dimensions as mockup photo)
                     */
                    overImage: number | Media;
                    ovrlyTyp?: ('lighting' | 'shadow' | 'reflection' | 'ambient') | null;
                    overbldMde?: ('overlay' | 'multiply' | 'screen' | 'soft-light' | 'hard-light') | null;
                    /**
                     * Overlay strength (0.1 = subtle, 0.8 = strong)
                     */
                    ovlayOpa?: number | null;
                    /**
                     * Specific area (leave empty for entire mockup)
                     */
                    overlayArea?: string | null;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Control rendering engine and quality settings
               */
              render?: {
                /**
                 * Auto selects best engine based on complexity
                 */
                pfEngine?: ('auto' | 'canvas' | 'pixi') | null;
                /**
                 * Enable displacement, masking, and lighting effects
                 */
                enableAdvancedEffects?: boolean | null;
                quality?: ('draft' | 'standard' | 'high' | 'ultra') | null;
                /**
                 * Export resolution multiplier (1x to 4x for print)
                 */
                exportRes?: number | null;
                /**
                 * Show rendering progress to users
                 */
                enableProgTrack?: boolean | null;
              };
              fbrcProp?: {
                mfab?:
                  | ('cotton' | 'polyester' | 'cotton_blend' | 'canvas' | 'leather' | 'denim' | 'fleece' | 'jersey')
                  | null;
                fabricWeight?: number | null;
                Texture?: ('smooth' | 'textured' | 'rough' | 'glossy' | 'matte') | null;
                stretchability?: number | null;
                transparency?: number | null;
              };
              lightingConditions?: {
                lightDirection?: number | null;
                lightIntensity?: number | null;
                ambientLight?: number | null;
                shadowIntensity?: number | null;
              };
              area?:
                | {
                    areaName: string;
                    visibility?: ('full' | 'partial' | 'edge' | 'sleeve' | 'shadow' | 'reflection') | null;
                    /**
                     * Percentage of area visible (0-100%)
                     */
                    visibilityPercentage?: number | null;
                    Config?: {
                      enableMasking?: boolean | null;
                      mask?: ('gradient' | 'sharp' | 'soft' | 'svg' | 'fold' | 'seam') | null;
                      /**
                       * SVG path data for custom masking
                       */
                      maskPath?: string | null;
                    };
                    grdnmsk?: {
                      grdn?: ('horizontal' | 'vertical' | 'radial' | 'angle') | null;
                      gradientAngle?: number | null;
                      /**
                       * Where fade starts (0-1)
                       */
                      fadeStart?: number | null;
                      /**
                       * Where fade ends (0-1)
                       */
                      fadeEnd?: number | null;
                      fadeIntensity?: number | null;
                    };
                    edgeDetectionSettings?: {
                      enableEdgeDetection?: boolean | null;
                      edgeThreshold?: number | null;
                      /**
                       * Edge softness in pixels
                       */
                      edgeSoftness?: number | null;
                    };
                    fbrc?: {
                      enableFabricBlend?: boolean | null;
                      bfab?: ('cotton' | 'polyester' | 'canvas' | 'leather' | 'denim') | null;
                      foldAwareness?: boolean | null;
                      seamAwareness?: boolean | null;
                      textureIntensity?: number | null;
                      fabricColor?: string | null;
                      fabricRoughness?: number | null;
                    };
                    design: {
                      /**
                       * X position (0.0-1.0)
                       */
                      coordinateX: number;
                      /**
                       * Y position (0.0-1.0)
                       */
                      coordinateY: number;
                      /**
                       * Width (0.0-1.0)
                       */
                      coordinateWidth: number;
                      /**
                       * Height (0.0-1.0)
                       */
                      coordinateHeight: number;
                      rotation?: number | null;
                      skewX?: number | null;
                      skewY?: number | null;
                      scaleX?: number | null;
                      scaleY?: number | null;
                      blend?: ('normal' | 'multiply' | 'screen' | 'overlay' | 'soft_light') | null;
                      opacity?: number | null;
                      preserveColors?: boolean | null;
                    };
                    uvMap?: {
                      srfc?: ('planar' | 'cylinder' | 'frustum' | 'sphere' | 'mesh') | null;
                      uStart?: number | null;
                      vStart?: number | null;
                      uSpan?: number | null;
                      vSpan?: number | null;
                      uRepeat?: number | null;
                      vRepeat?: number | null;
                      rotationDeg?: number | null;
                      orn?: {
                        type?: ('feature' | 'angle' | 'pixel') | null;
                        featureName?: string | null;
                        angleDeg?: number | null;
                        pixelX?: number | null;
                      };
                      wrpmdU?: ('clamp' | 'repeat' | 'mirror') | null;
                      wpmdV?: ('clamp' | 'repeat' | 'mirror') | null;
                    };
                    surfaceWrapSettings?: {
                      enableWrap?: boolean | null;
                      wrapAngle?: number | null;
                      wrapIntensity?: number | null;
                      dynamicWrap?: boolean | null;
                      wrapFalloff?: number | null;
                    };
                    perspectiveSettings?: {
                      enablePerspective?: boolean | null;
                      perspectiveIntensity?: number | null;
                      dynamicPerspective?: boolean | null;
                    };
                    fbrEft?: {
                      enableFolds?: boolean | null;
                      foldIntensity?: number | null;
                      fold?: ('horizontal' | 'vertical' | 'radial' | 'random') | null;
                      seamDistrt?: boolean | null;
                      /**
                       * Fabric depth effect in pixels
                       */
                      fabricDpth?: number | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              priority?: number | null;
              tags?:
                | {
                    tag?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        custAreas?:
          | {
              areaId?: string | null;
              areaName: string;
              areaType?: ('primary' | 'secondary' | 'accent' | 'sleeve' | 'back' | 'pocket') | null;
              'Minimum printing price'?: string | null;
              'Per sq inch printing price'?: string | null;
              canvasDim: {
                widthInch: number;
                heightInch: number;
                canvasPixWid?: number | null;
                canvasPixHeight?: number | null;
                aspectRatioLocked?: boolean | null;
              };
              designCanvasPhotos?:
                | {
                    photo: number | Media;
                    photoColor?: string | null;
                    printAreaCoord?: {
                      x?: number | null;
                      y?: number | null;
                      width?: number | null;
                      height?: number | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              restrictions?: {
                minElementSize?: {
                  width?: number | null;
                  height?: number | null;
                };
                maxElements?: number | null;
              };
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  areaSynchRules?:
    | {
        ruleName: string;
        sourceArea: string;
        targetAreas?:
          | {
              area?: string | null;
              id?: string | null;
            }[]
          | null;
        syncType?: ('copy' | 'mirror_h' | 'mirror_v' | 'scale') | null;
        id?: string | null;
      }[]
    | null;
  displayImages?:
    | {
        image: number | Media;
        title?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  prodInt: {
    /**
     * Choose smart template or let AI auto-detect from your mockup images
     */
    prodTemp:
      | 'auto_detect'
      | 'apparel_tshirt_standard'
      | 'apparel_tshirt_folded'
      | 'apparel_hoodie_front'
      | 'apparel_hoodie_lifestyle'
      | 'phone_iphone15pro'
      | 'phone_iphone14'
      | 'phone_samsung_s24'
      | 'phone_pixel'
      | 'mug_standard'
      | 'tumbler_travel'
      | 'pillow_square'
      | 'canvas_standard'
      | 'bag_tote'
      | 'custom';
    autoDetSett?: {
      /**
       * Automatically analyze uploaded mockup images to detect customizable areas
       */
      enImgAnal?: boolean | null;
      anAcc?: ('fast' | 'balanced' | 'precise' | 'ultra') | null;
      /**
       * Minimum confidence level for auto-detected areas (0.1 = low, 1.0 = very high)
       */
      detThres?: number | null;
      /**
       * Require manual review of auto-detected areas before activation
       */
      manlReq?: boolean | null;
    };
    srtDef?: {
      /**
       * Use smart defaults from selected product template
       */
      intfrmTlt?: boolean | null;
      oMskRls?: {
        /**
         * Automatically create masks for edge transitions, sleeves, and occlusions
         */
        enablesMask?: boolean | null;
        edgeDetctMode?: ('automatic' | 'geometric' | 'color' | 'contrast' | 'ml') | null;
        occlDetct?: {
          /**
           * Automatically detect and mask camera holes in phone cases
           */
          detectCamHole?: boolean | null;
          /**
           * Automatically detect seam lines in apparel
           */
          detectSeams?: boolean | null;
          /**
           * Automatically detect fabric folds and wrinkles
           */
          detectFolds?: boolean | null;
          /**
           * Automatically detect shadow areas for realistic rendering
           */
          detectShadows?: boolean | null;
        };
      };
    };
  };
  PrntTch?:
    | {
        id?: string | null;
        technologyName: 'dtg' | 'dtf' | 'screen' | 'sublimation' | 'embroidery' | 'vinyl' | 'digital' | 'uv' | 'laser';
        /**
         * Upload mockup photos and let AI detect customizable areas automatically
         */
        smtMckpPht?:
          | {
              /**
               * e.g., "Front View", "Folded Style", "Lifestyle Shot"
               */
              title?: string | null;
              /**
               * Upload high-quality mockup image (AI will analyze automatically)
               */
              photo: number | Media;
              view?:
                | (
                    | 'front'
                    | 'back'
                    | 'left'
                    | 'right'
                    | 'three_quarter_front_left'
                    | 'three_quarter_front_right'
                    | 'folded'
                    | 'lifestyle'
                    | 'detail'
                    | 'top'
                  )
                | null;
              mock?: ('studio' | 'lifestyle' | 'model' | 'flat_lay' | 'folded' | 'detail') | null;
              /**
               * Base color of the product in this mockup
               */
              photoColor: string;
              /**
               * Automatically populated by AI image analysis
               */
              Anl?: {
                Sts?: ('pending' | 'processing' | 'completed' | 'failed' | 'needs_review') | null;
                /**
                 * AI-detected product type
                 */
                detProdTy?: string | null;
                /**
                 * AI confidence level (0-1)
                 */
                confScore?: number | null;
                /**
                 * AI-detected customizable areas
                 */
                detAr?:
                  | {
                      arNme?: string | null;
                      bodBx?: {
                        x?: number | null;
                        y?: number | null;
                        width?: number | null;
                        height?: number | null;
                      };
                      confdnce?: number | null;
                      /**
                       * AI-suggested masking path (SVG)
                       */
                      suggesMask?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                /**
                 * AI-detected obstructions (camera holes, seams, etc.)
                 */
                dtc?:
                  | {
                      obs?:
                        | ('camera_hole' | 'speaker_hole' | 'seam' | 'port' | 'button' | 'fold' | 'shadow' | 'unknown')
                        | null;
                      boundbox?: {
                        x?: number | null;
                        y?: number | null;
                        width?: number | null;
                        height?: number | null;
                      };
                      confidence?: number | null;
                      id?: string | null;
                    }[]
                  | null;
              };
              /**
               * AI-detected areas with smart defaults + manual overrides
               */
              Vsa?:
                | {
                    /**
                     * Area name (auto-populated from AI or manual entry)
                     */
                    areaName: string;
                    /**
                     * How this area configuration was created
                     */
                    Src?: ('ai_detected' | 'template' | 'manual' | 'hybrid') | null;
                    /**
                     * Manual review status for AI-detected areas
                     */
                    apStt?: ('pending_review' | 'approved' | 'rejected' | 'needs_adjustment') | null;
                    vsblty?:
                      | ('full' | 'partial' | 'edge' | 'sleeve' | 'shadow' | 'reflection' | 'device_cutout')
                      | null;
                    /**
                     * Percentage of area visible (AI can auto-calculate)
                     */
                    visibilityPercentage?: number | null;
                    smrt?: {
                      /**
                       * Use AI-powered smart masking for this area
                       */
                      enableSmartMask?: boolean | null;
                      Srtgy?: ('ai_automatic' | 'template' | 'manual' | 'hybrid') | null;
                    };
                    Msk?: {
                      edg?: ('soft' | 'medium' | 'sharp' | 'ultra') | null;
                      /**
                       * Automatically adapt masking based on lighting conditions
                       */
                      adaptToLighting?: boolean | null;
                      /**
                       * Consider fabric properties when creating masks
                       */
                      fabricAwareness?: boolean | null;
                      /**
                       * Automatically detect and handle seam lines
                       */
                      seamDetection?: boolean | null;
                    };
                    /**
                     * Automatically generated by AI analysis
                     */
                    gnMsk?: {
                      /**
                       * SVG path for the generated mask
                       */
                      maskPath?: string | null;
                      mskTyp?: ('gradient' | 'vector' | 'bitmap' | 'composite') | null;
                      /**
                       * AI confidence in generated mask quality
                       */
                      maskConfidence?: number | null;
                    };
                    smartPlacement?: {
                      /**
                       * X position (AI-calculated)
                       */
                      autoX?: number | null;
                      /**
                       * Y position (AI-calculated)
                       */
                      autoY?: number | null;
                      /**
                       * Width (AI-calculated)
                       */
                      autoWidth?: number | null;
                      /**
                       * Height (AI-calculated)
                       */
                      autoHeight?: number | null;
                      /**
                       * Override AI-calculated placement with manual values
                       */
                      enableManualOverride?: boolean | null;
                      manualX?: number | null;
                      manualY?: number | null;
                      manualWidth?: number | null;
                      manualHeight?: number | null;
                      rotation?: number | null;
                      skewX?: number | null;
                      skewY?: number | null;
                      scaleX?: number | null;
                      scaleY?: number | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              /**
               * Display priority (higher numbers appear first)
               */
              priority?: number | null;
              tags?:
                | {
                    tag?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * AI-enhanced customization areas with smart defaults
         */
        smtCstmtnAr?:
          | {
              areaId?: string | null;
              /**
               * e.g., "Front", "Back", "Left Sleeve", "Camera Area"
               */
              areaName: string;
              areaType?: ('primary' | 'secondary' | 'accent' | 'sleeve' | 'back' | 'pocket' | 'device_specific') | null;
              smartCanvasConfig?: {
                /**
                 * Use AI-calculated optimal dimensions for this area
                 */
                useAICalculatedDimensions?: boolean | null;
                aiWidthInches?: number | null;
                aiHeightInches?: number | null;
                aiCanvasPixelWidth?: number | null;
                aiCanvasPixelHeight?: number | null;
                manualWidthInches?: number | null;
                manualHeightInches?: number | null;
                manualCanvasPixelWidth?: number | null;
                manualCanvasPixelHeight?: number | null;
                aspectRatioLocked?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'blank-products';
        value: number | BlankProduct;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heroImage?: T;
  featuredCategory?: T;
  StudioCategory?: T;
  products?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blank-products_select".
 */
export interface BlankProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  productType?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  brand?: T;
  brandSku?: T;
  sku?: T;
  'Manufacturer sku'?: T;
  vendorInfo?:
    | T
    | {
        supplier?: T;
        supplierProductId?: T;
        countryOrigin?: T;
      };
  sourcing?:
    | T
    | {
        minOrderQty?: T;
        leadTimeDays?: T;
        shipTimeDays?: T;
        rushAvailable?: T;
        rushLeadTimeDays?: T;
      };
  cost?: T;
  'GST Cost'?: T;
  pricing?:
    | T
    | {
        markupType?: T;
        markupValue?: T;
        suggestedRetail?: T;
      };
  pricingTiers?:
    | T
    | {
        minQuantity?: T;
        maxQuantity?: T;
        markupPercentage?: T;
        id?: T;
      };
  additionalCosts?:
    | T
    | {
        printingCostPerArea?: T;
        printingGST?: T;
        setupFee?: T;
        rushSurcharge?: T;
      };
  description?: T;
  features?: T;
  HSNCode?: T;
  materials?:
    | T
    | {
        primary?: T;
        weight?: T;
        construction?: T;
        finish?: T;
        efabType?: T;
        fabricWeight?: T;
        surfaceTexture?: T;
        stretchability?: T;
        transparency?: T;
        reflectivity?: T;
      };
  careInstructions?:
    | T
    | {
        instruction?: T;
        icon?: T;
        id?: T;
      };
  physicalDimensions?:
    | T
    | {
        widthInches?: T;
        heightInches?: T;
        depthInches?: T;
        diameter?: T;
        units?: T;
      };
  shippingInfo?:
    | T
    | {
        weight?: T;
        shippingDimensions?: T;
        shippingCharges?: T;
        shippingLocationID?: T;
        shippingProfileID?: T;
        packageType?: T;
      };
  colorOptions?:
    | T
    | {
        colorName?: T;
        colorHex?: T;
        colorSku?: T;
        isPrimary?: T;
        fabricInteraction?:
          | T
          | {
              absorptionRate?: T;
              blendMode?: T;
              colorShift?:
                | T
                | {
                    hueShift?: T;
                    saturationShift?: T;
                    lightnessShift?: T;
                  };
            };
        id?: T;
      };
  color_Images?: T;
  sizeOptions?:
    | T
    | {
        sizeName?: T;
        sizeSku?: T;
        ExtraCost?: T;
        sizeDescription?: T;
        dimensions?:
          | T
          | {
              width?: T;
              height?: T;
            };
        id?: T;
      };
  size_Images?: T;
  sizeChart?: T;
  sizeChartHtml?: T;
  surfConf?:
    | T
    | {
        No_Mockup_Compatible?: T;
        renderType?: T;
        surfProp?:
          | T
          | {
              wrapAngle?: T;
              curveInten?: T;
              designRatio?:
                | T
                | {
                    widthRatio?: T;
                    heightRatio?: T;
                  };
            };
        blendSet?:
          | T
          | {
              defaultBlendMode?: T;
              defaultOpacity?: T;
              preserveColors?: T;
            };
      };
  advanSurfMap?:
    | T
    | {
        curvProf?: T;
        barrelDist?: T;
        pincushiDistor?: T;
        perspDis?: T;
        hasSeams?: T;
      };
  seamPositions?:
    | T
    | {
        seamTypes?: T;
        positionX?: T;
        positionY?: T;
        width?: T;
        seamEffect?: T;
        id?: T;
      };
  lightingConfiguration?:
    | T
    | {
        lightDirection?: T;
        lightIntensity?: T;
        ambientLight?: T;
        shadowIntensity?: T;
      };
  printT?:
    | T
    | {
        id?: T;
        technologyName?: T;
        printingConstraints?:
          | T
          | {
              dpiRequirements?:
                | T
                | {
                    minimum?: T;
                    recommended?: T;
                    maximum?: T;
                  };
              sizeLimits?:
                | T
                | {
                    minWidthInch?: T;
                    minHeightInch?: T;
                    maxWidthInch?: T;
                    maxHeightInch?: T;
                  };
              colorLimits?:
                | T
                | {
                    maxColors?: T;
                    supportsFullColor?: T;
                  };
              printBleeds?:
                | T
                | {
                    bleedMargin?: T;
                    safetyMargin?: T;
                    trimTolerance?: T;
                  };
            };
        mockupPhotos?:
          | T
          | {
              title?: T;
              photo?: T;
              mocwidthpx?: T;
              mochigtpx?: T;
              tmbwidthpx?: T;
              tmbhigtpx?: T;
              viewAngle?: T;
              mockupType?: T;
              photoColor?: T;
              photoSize?: T;
              dispMaps?:
                | T
                | {
                    dispImg?: T;
                    dsrface?: T;
                    disint?: T;
                    disarea?: T;
                    id?: T;
                  };
              alpMasks?:
                | T
                | {
                    maskImg?: T;
                    alfarea?: T;
                    alfmask?: T;
                    featherEdge?: T;
                    id?: T;
                  };
              light?:
                | T
                | {
                    overImage?: T;
                    ovrlyTyp?: T;
                    overbldMde?: T;
                    ovlayOpa?: T;
                    overlayArea?: T;
                    id?: T;
                  };
              render?:
                | T
                | {
                    pfEngine?: T;
                    enableAdvancedEffects?: T;
                    quality?: T;
                    exportRes?: T;
                    enableProgTrack?: T;
                  };
              fbrcProp?:
                | T
                | {
                    mfab?: T;
                    fabricWeight?: T;
                    Texture?: T;
                    stretchability?: T;
                    transparency?: T;
                  };
              lightingConditions?:
                | T
                | {
                    lightDirection?: T;
                    lightIntensity?: T;
                    ambientLight?: T;
                    shadowIntensity?: T;
                  };
              area?:
                | T
                | {
                    areaName?: T;
                    visibility?: T;
                    visibilityPercentage?: T;
                    Config?:
                      | T
                      | {
                          enableMasking?: T;
                          mask?: T;
                          maskPath?: T;
                        };
                    grdnmsk?:
                      | T
                      | {
                          grdn?: T;
                          gradientAngle?: T;
                          fadeStart?: T;
                          fadeEnd?: T;
                          fadeIntensity?: T;
                        };
                    edgeDetectionSettings?:
                      | T
                      | {
                          enableEdgeDetection?: T;
                          edgeThreshold?: T;
                          edgeSoftness?: T;
                        };
                    fbrc?:
                      | T
                      | {
                          enableFabricBlend?: T;
                          bfab?: T;
                          foldAwareness?: T;
                          seamAwareness?: T;
                          textureIntensity?: T;
                          fabricColor?: T;
                          fabricRoughness?: T;
                        };
                    design?:
                      | T
                      | {
                          coordinateX?: T;
                          coordinateY?: T;
                          coordinateWidth?: T;
                          coordinateHeight?: T;
                          rotation?: T;
                          skewX?: T;
                          skewY?: T;
                          scaleX?: T;
                          scaleY?: T;
                          blend?: T;
                          opacity?: T;
                          preserveColors?: T;
                        };
                    uvMap?:
                      | T
                      | {
                          srfc?: T;
                          uStart?: T;
                          vStart?: T;
                          uSpan?: T;
                          vSpan?: T;
                          uRepeat?: T;
                          vRepeat?: T;
                          rotationDeg?: T;
                          orn?:
                            | T
                            | {
                                type?: T;
                                featureName?: T;
                                angleDeg?: T;
                                pixelX?: T;
                              };
                          wrpmdU?: T;
                          wpmdV?: T;
                        };
                    surfaceWrapSettings?:
                      | T
                      | {
                          enableWrap?: T;
                          wrapAngle?: T;
                          wrapIntensity?: T;
                          dynamicWrap?: T;
                          wrapFalloff?: T;
                        };
                    perspectiveSettings?:
                      | T
                      | {
                          enablePerspective?: T;
                          perspectiveIntensity?: T;
                          dynamicPerspective?: T;
                        };
                    fbrEft?:
                      | T
                      | {
                          enableFolds?: T;
                          foldIntensity?: T;
                          fold?: T;
                          seamDistrt?: T;
                          fabricDpth?: T;
                        };
                    id?: T;
                  };
              priority?: T;
              tags?:
                | T
                | {
                    tag?: T;
                    id?: T;
                  };
              id?: T;
            };
        custAreas?:
          | T
          | {
              areaId?: T;
              areaName?: T;
              areaType?: T;
              'Minimum printing price'?: T;
              'Per sq inch printing price'?: T;
              canvasDim?:
                | T
                | {
                    widthInch?: T;
                    heightInch?: T;
                    canvasPixWid?: T;
                    canvasPixHeight?: T;
                    aspectRatioLocked?: T;
                  };
              designCanvasPhotos?:
                | T
                | {
                    photo?: T;
                    photoColor?: T;
                    printAreaCoord?:
                      | T
                      | {
                          x?: T;
                          y?: T;
                          width?: T;
                          height?: T;
                        };
                    id?: T;
                  };
              restrictions?:
                | T
                | {
                    minElementSize?:
                      | T
                      | {
                          width?: T;
                          height?: T;
                        };
                    maxElements?: T;
                  };
              id?: T;
            };
      };
  areaSynchRules?:
    | T
    | {
        ruleName?: T;
        sourceArea?: T;
        targetAreas?:
          | T
          | {
              area?: T;
              id?: T;
            };
        syncType?: T;
        id?: T;
      };
  displayImages?:
    | T
    | {
        image?: T;
        title?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  prodInt?:
    | T
    | {
        prodTemp?: T;
        autoDetSett?:
          | T
          | {
              enImgAnal?: T;
              anAcc?: T;
              detThres?: T;
              manlReq?: T;
            };
        srtDef?:
          | T
          | {
              intfrmTlt?: T;
              oMskRls?:
                | T
                | {
                    enablesMask?: T;
                    edgeDetctMode?: T;
                    occlDetct?:
                      | T
                      | {
                          detectCamHole?: T;
                          detectSeams?: T;
                          detectFolds?: T;
                          detectShadows?: T;
                        };
                  };
            };
      };
  PrntTch?:
    | T
    | {
        id?: T;
        technologyName?: T;
        smtMckpPht?:
          | T
          | {
              title?: T;
              photo?: T;
              view?: T;
              mock?: T;
              photoColor?: T;
              Anl?:
                | T
                | {
                    Sts?: T;
                    detProdTy?: T;
                    confScore?: T;
                    detAr?:
                      | T
                      | {
                          arNme?: T;
                          bodBx?:
                            | T
                            | {
                                x?: T;
                                y?: T;
                                width?: T;
                                height?: T;
                              };
                          confdnce?: T;
                          suggesMask?: T;
                          id?: T;
                        };
                    dtc?:
                      | T
                      | {
                          obs?: T;
                          boundbox?:
                            | T
                            | {
                                x?: T;
                                y?: T;
                                width?: T;
                                height?: T;
                              };
                          confidence?: T;
                          id?: T;
                        };
                  };
              Vsa?:
                | T
                | {
                    areaName?: T;
                    Src?: T;
                    apStt?: T;
                    vsblty?: T;
                    visibilityPercentage?: T;
                    smrt?:
                      | T
                      | {
                          enableSmartMask?: T;
                          Srtgy?: T;
                        };
                    Msk?:
                      | T
                      | {
                          edg?: T;
                          adaptToLighting?: T;
                          fabricAwareness?: T;
                          seamDetection?: T;
                        };
                    gnMsk?:
                      | T
                      | {
                          maskPath?: T;
                          mskTyp?: T;
                          maskConfidence?: T;
                        };
                    smartPlacement?:
                      | T
                      | {
                          autoX?: T;
                          autoY?: T;
                          autoWidth?: T;
                          autoHeight?: T;
                          enableManualOverride?: T;
                          manualX?: T;
                          manualY?: T;
                          manualWidth?: T;
                          manualHeight?: T;
                          rotation?: T;
                          skewX?: T;
                          skewY?: T;
                          scaleX?: T;
                          scaleY?: T;
                        };
                    id?: T;
                  };
              priority?: T;
              tags?:
                | T
                | {
                    tag?: T;
                    id?: T;
                  };
              id?: T;
            };
        smtCstmtnAr?:
          | T
          | {
              areaId?: T;
              areaName?: T;
              areaType?: T;
              smartCanvasConfig?:
                | T
                | {
                    useAICalculatedDimensions?: T;
                    aiWidthInches?: T;
                    aiHeightInches?: T;
                    aiCanvasPixelWidth?: T;
                    aiCanvasPixelHeight?: T;
                    manualWidthInches?: T;
                    manualHeightInches?: T;
                    manualCanvasPixelWidth?: T;
                    manualCanvasPixelHeight?: T;
                    aspectRatioLocked?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Add child navigation items that will appear in the dropdown
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'categories';
                      value: number | Category;
                    } | null);
                url?: string | null;
                label: string;
              };
              /**
               * Add sub-items (third level navigation)
               */
              subChildren?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: number | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: number | Post;
                          } | null)
                        | ({
                            relationTo: 'categories';
                            value: number | Category;
                          } | null);
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              subChildren?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}